### ISSUE TITLE
Full artists from tracks

### ISSUE THREAD

**Issue by rshkv** [thefrenchhouse/spotify-graphql#55]
I'm loading tracks and for their artists, I'd like to show images and other [full artist](https://developer.spotify.com/web-api/object-model/#artist-object-full) properties, including related artists. However, tracks only come with [simplified artists](https://developer.spotify.com/web-api/object-model/#artist-object-simplified). I'm now thinking if it's easier to do the joins or contribute.

I assume the challenge is to register when the user is asking for full properties and then do extra requests. I glanced at the resolvers and [it looks like you're already doing something similar for tracks](https://github.com/thefrenchhouse/spotify-graphql/blob/master/lib/resolvers/track.ts#L16). I tried the following query in your new interactive console (👍): 
```
{
  track(name: "Little Bit of This") {
    name
    album {
      name
      label  // null
      popularity  // null
      release_date  // null 
    }
  }
}
```
I get autocomplete for the full object properties. But in the response everything that isn't in simplified albums is `null`. I'm not sure why, and I couldn't find where `variable.full` is set. 

Can you tell me what needed to be done in order to access full artists from tracks?

**Comment by wittydeveloper** [comment]
Hello @rshkv !

In fact, this is more complex than the `tracks.album` because for the album case I only have to do a API cal to `/v1/albums/{id}` using `track.album.id` (because `/v1/tracks/{id}/album` do not exists.

For the `tracks.artists` is more complicated because I'll have to iterate over `track.artists[].id` and manage to call `/v1/artists?ids={ids}` (considering that `ids` maxlength is 50)

It's totally feasible don't worry.
I'll also refactor the internal API to make more clear (especially to `limitConcurency` and `pooling` things!)


I'll keep you updated, this will be done in the week-end 
Cheers 👋

**Comment by rshkv** [comment]
I understand. Looking forward to it! 😀

**Comment by wittydeveloper** [comment]
@rshkv Sorry, I did not have the time this week end to work on it, I'll try to fix it today.

**Comment by wittydeveloper** [comment]
Hi @rshkv 

sorry for the delay, I had a lot of work on the other side and I found a lot of "bugs" while adding this features

### Result now:

<img width="1431" alt="screen shot 2017-04-11 at 14 11 33" src="https://cloud.githubusercontent.com/assets/1252066/24908678/324e8112-1ec1-11e7-88be-895d4b2b82dc.png">
<img width="1433" alt="screen shot 2017-04-11 at 14 11 42" src="https://cloud.githubusercontent.com/assets/1252066/24908676/324a7fe0-1ec1-11e7-973a-02f5daece859.png">
<img width="1435" alt="screen shot 2017-04-11 at 14 12 42" src="https://cloud.githubusercontent.com/assets/1252066/24908677/324ab820-1ec1-11e7-8a29-fb5061816375.png">

**Comment by rshkv** [comment]
Don't worry, thank you very much 🙂
